# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: git_repo_found.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14git_repo_found.proto\x12\x1binfrastructure.network.grpc\"\xe6\x01\n\x0cGitRepoFound\x12\x14\n\x0cpackage_name\x18\x01 \x01(\t\x12\x17\n\x0fpackage_version\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x0b\n\x03tag\x18\x04 \x01(\t\x12I\n\x08metadata\x18\x05 \x03(\x0b\x32\x37.infrastructure.network.grpc.GitRepoFound.MetadataEntry\x12\x11\n\tsubfolder\x18\x06 \x01(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"&\n\x05Reply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\x83\x01\n\x13GitRepoFoundService\x12l\n\x19GitRepoFoundNotifications\x12).infrastructure.network.grpc.GitRepoFound\x1a\".infrastructure.network.grpc.Reply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'git_repo_found_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GITREPOFOUND_METADATAENTRY._options = None
  _GITREPOFOUND_METADATAENTRY._serialized_options = b'8\001'
  _GITREPOFOUND._serialized_start=54
  _GITREPOFOUND._serialized_end=284
  _GITREPOFOUND_METADATAENTRY._serialized_start=237
  _GITREPOFOUND_METADATAENTRY._serialized_end=284
  _REPLY._serialized_start=286
  _REPLY._serialized_end=324
  _GITREPOFOUNDSERVICE._serialized_start=327
  _GITREPOFOUNDSERVICE._serialized_end=458
# @@protoc_insertion_point(module_scope)
