# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rydnr.tools.nix.flake.python_generator.infrastructure.network.grpc.git_repo_found_pb2 as git__repo__found__pb2


class GitRepoFoundServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GitRepoFoundNotifications = channel.unary_unary(
            "/infrastructure.network.grpc.GitRepoFoundService/GitRepoFoundNotifications",
            request_serializer=git__repo__found__pb2.GitRepoFound.SerializeToString,
            response_deserializer=git__repo__found__pb2.Reply.FromString,
        )


class GitRepoFoundServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GitRepoFoundNotifications(self, request, context):
        """Receive a git_repo_found event"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GitRepoFoundServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GitRepoFoundNotifications": grpc.unary_unary_rpc_method_handler(
            servicer.GitRepoFoundNotifications,
            request_deserializer=git__repo__found__pb2.GitRepoFound.FromString,
            response_serializer=git__repo__found__pb2.Reply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "infrastructure.network.grpc.GitRepoFoundService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class GitRepoFoundService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GitRepoFoundNotifications(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/infrastructure.network.grpc.GitRepoFoundService/GitRepoFoundNotifications",
            git__repo__found__pb2.GitRepoFound.SerializeToString,
            git__repo__found__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
